### ISSUE TITLE
don't work with rails 4.2

### ISSUE THREAD

**Issue by net1957** [kbaum/browser-timezone-rails#17]
if I  update the gemfile to include
 ````
gem 'browser-timezone-rails', '~> 0.1'
````

I get:
````
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    browser-timezone-rails (~> 0.1) x64-mingw32 depends on
      jstz-rails (>= 0) x64-mingw32 depends on
        railties (~> 3.1) x64-mingw32

    rails (= 4.2.0) x64-mingw32 depends on
      railties (4.2.0)
````

Seems that jstz-rails don't support rails 4.2

previous version 0.0.8 install without a problem.

**Comment by kbaum** [comment]
Guess we'll have to upgrade jstz-rails.  Any idea whats needed?

**Comment by net1957** [comment]
Perhaps change the dependency on  railties ~3.1 to railties >=3.1 ? but I'm not sure what require this.

**Comment by simonbogarde** [comment]
@net1957 It seems that the distributed gem requires railties 3.1, whereas the repository allows anything >= 3.1. Did you contact the owner? 
I quickfixed this for me by adding "gem 'jstz-rails',  github: 'vanetten/jstz-rails'" to my Gemfile.

**Comment by kbaum** [comment]
@simonbogarde, @net1957 - Looks like jstz-rails simply needs to cut a new Gem.

https://github.com/vanetten/jstz-rails/commit/3c5d5730f5891d1ed4656058f201fdc557792710

**Comment by kevindewalt** [comment]
Same issue here.

**Comment by korun** [comment]
Same issue. :)

**Comment by fabn** [comment]
Even better, since jstz-rails seems unmaintained why don't you include the javascript in this gem directly? In this way you have full control on that.

**Comment by kbaum** [comment]
@fabn - i forked jstz-rails and changed dependency to be on that fork. Let me know if that works.

Thanks!

**Comment by fabn** [comment]
@kbaum I'll try that. If I may advice, I'd rather embed the js for the following reasons:

* You're [already providing assets](https://github.com/kbaum/browser-timezone-rails/blob/master/app/assets/javascripts/browser_timezone_rails/set_time_zone.js.coffee) for this gem so there is no drawback to add another javascript
* In this way you'll have to (possibly) update two different gems in order to release a new version
* When installing gem with `bundle install` bundler will need to consider another gem in its dependencies graph, this will slow down dependency resolution.

In this case I think the impact will be minimal but since there's no advantage to keep two distinct gems I'd bring in the javascript file directly.

Just my two cents.

**Comment by kbaum** [comment]
Makes complete sense.



—

**Comment by fabn** [comment]
This is also very important to upgrade to rails 4.2 so if you cut a new release please include this.

Thanks.

**Comment by chr0n1x** [comment]
bump

**Comment by kbaum** [comment]
I think this has been addressed with the latest release.
